### ISSUE TITLE
Add helm charts for deployment

### ISSUE THREAD

**Issue by ianarsenault** [jaydeluca/sre-lab#14]

**Comment by jaydeluca** [comment]
i made some progress on this one and created helm charts (and/or terraform modules that use them) for the primary components:

-  Postgres
-  Orders Migrations
-  Orders Api
-  Users Api
-  Load test
- SigNoz

I also ended up creating #23 because it got a little confusing navigating between `k8s/charts` and `terraform/k8s` and I'm wondering if there's a better way to organize things. Will try and brainstorm a better structure in that other issue thread. There's still some missing pieces for helm, but otherwise I think we can close this issue and open new ones for any other additional work.
